import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import NavbarHome from "./navbarhome/page";
import SubTitleText from "./components/SubTitleText";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
          <section className="flex">
            <NavbarHome/>
            <div className="flex-1">
              <SubTitleText></SubTitleText>
              {children}
            </div>
          </section>
        </Providers>
      </body>
    </html>
  );
}
